### ISSUE TITLE
Get current iteration from VisitStoredFields

### ISSUE THREAD

**Issue by panakour** [blugelabs/bluge#100]
I think It would be nice if `type StoredFieldVisitor func(field string, value []byte) bool` also has the argument of the current loop iteration. This may be useful for someone to want to hook some custom logic in specific iterator or in my own issue bellow.

Now these loops has blank identifiers
![image](https://user-images.githubusercontent.com/12927166/154847696-728bf19a-b487-4183-94c7-f5b4d26c20af.png)
https://github.com/blugelabs/bluge/blob/f34c4accbd91d52d6896d1dbab744987c9e71450/index/snapshot.go#L294

In my own case I want this because I want to preallocate a slice and then assign each field something like: 
```
func (r Results) MatchFields(documentMatch *search.DocumentMatch) error {
	match := make([]*DocumentMatch, documentMatch.HitNumber)
	err := documentMatch.VisitStoredFields(func(field string, value []byte, index int) bool {
		switch field {
		case "field1":
			match[index].ID = string(value)
		case "field2":
			match[index].Type = string(value)
		default:
			match[index].DocValues[field] = append(match.DocValues[field], value)
			match[index].Values[field] = string(value)
		}
		return true
	})
	if err != nil {
		return fmt.Errorf("error accessing stored fields: %w", err)
	}
	return nil
}

```

**Comment by mschoch** [comment]
I am a bit confused about what you are trying to do.

In the first section, you remarked that the identifiers in the loop were blank.  First, it should be pointed out that this particular loop shown here is only for the virtual fields, not the actual document fields.  When you visit stored fields, both are processed, you can see that line 308 also invokes the visitor function:

https://github.com/blugelabs/bluge/blob/f34c4accbd91d52d6896d1dbab744987c9e71450/index/snapshot.go#L297-L309

So, at this point you see that we can't just use the loop iteration variable, as that only exists for the virtual fields.  The actual iteration over the fields takes place inside the segment code, making this a deeper change.

But, let's go back to what you were trying to do.  First, this line:

```
match := make([]*DocumentMatch, documentMatch.HitNumber)
```

Here you create a slice of *DocumentMatch, with the size set to the hit number of this document.  This line doesn't make sense to me.  The hit number simply serves to count/identify each hit produced by the search.  The first hit will be 1, the second 2, etc.  Unless you are looking at the last DocumentMatch, the HitNumber would not make sense to use for sizing the slice.

Next, you show the new "index" argument being used to refer to items inside the match slice.  But, again there seems to be a mismatch here, as the index you proposed would be incremented for each field visited, but the match slice contains documents, not fields.

Perhaps there is some confusion about what HitNumber is used for, or perhaps I'm just still not clear what you're trying to do.

**Comment by mschoch** [comment]
So, I understand your concern, and using appropriately sized slices can be a useful technique.  Whether or not it this makes a significant difference in your application is something you would have to measure.

First, since you are using a TopN search with aggregations enabled, you can determine how many hits will be returned with the following logic.

```
r.Hits = make([]*DocumentMatch, int(blugeResponse.Aggregations().Count()))
```

Then you can just keep your own counter, as you process results with `blugeResponse.Next()`, you can directly set values into `hits[counter] = ...`

Now, in the earlier code, you were also tracking stored fields in another slice (named DocValues, but I would suggest you not use that name as DocValues are different from stored fields).  There is no way to know how many stored fields will be returned before accessing them, so you will not be able to preallocate a slice and be sure it is large enough.  If your documents have some well known schema, and you know documents will always have at least N stored fields, you could preallocate a slice with that capacity (not size), and then continue to use append().  This will at least avoid reallocating the backing slice, when there are no more than N fields.

**Comment by panakour** [comment]
@mschoch thanks a lot for your quick answer. This is exactly what I was looking for.

**Comment by mschoch** [comment]
Oops, there is one more detail I messed up.

The value returned by Count() is the total number of hits, which if greater than s.FirstNItems, means that you'll only actually get s.FirstNItems items returned to you.

So you should do something like:

```
totalHits = int(blugeResponse.Aggregations().Count())
numHits = s.FirstNItems
if totalHits < numHits {
  numHits = totalHits
}
r.Hits = make([]*DocumentMatch, numHits)
```
