### ISSUE TITLE
Multiple updates to the same id in one Batch result in multiple documents with the same id in the index

### ISSUE THREAD

**Issue by enex** [blugelabs/bluge#85]
While easy to fix and avoid, I wasn't expecting batches to write multiple values for the same ID in the index. It may be intentional? What are the reason for it? Anyway it can be avoided by using a map keyed by the ID and only writing the result to the batch.

**Comment by mschoch** [comment]
So, this was an intentional design change from Bleve.  Specifically, in Bluge it is *INVALID* to add documents with the same identifier to a single batch.  If you do so, it will fail to maintain the invariant that document identifiers are unique.

If we don't want to allow this, why don't we enforce it ourselves?  Simply because there are some use cases where you never have duplicates at all, and therefore having the batch implementation use a map internally to de-duplicate is not only unnecessary, it makes reusing batch objects essentially impossible.  The big downside is that it means applications must de-duplicate entries in the batch themselves.  In practice I have found this not to be a huge deal, but I understand this is an API pain point, and I'm willing to consider other options.

And obviously we have not found a way to correctly communicate this, as you have run into this issue..

In the future with generics, it might even be possible for us to have 2 batch impls (one dedups, and one doesn't) without a perf penalty.  But for now, we've opted to simply make Bluge more powerful/useful, at the expense of making this part harder.  If you have suggestions to improve this that don't involve giving up batch re-use I'm open to other ideas.

**Comment by enex** [comment]
Thanks for the fast reply. Yes that makes sense however it would be nice to have some comments on the batch struct or method [https://github.com/blugelabs/bluge/blob/master/index/batch.go](https://github.com/blugelabs/bluge/blob/master/index/batch.go) That would solve it in my opinion.

I somehow overlooked it in the docs [https://blugelabs.com/bluge/indexing](https://blugelabs.com/bluge/indexing/)
