### ISSUE TITLE
Is a Writer or a Reader safe for concurrent use by multiple goroutines

### ISSUE THREAD

**Issue by szxp** [blugelabs/bluge#95]
How much concurrency does a Writer or a Reader support?

**Comment by mschoch** [comment]
> Is a Writer or a Reader safe for concurrent use by multiple goroutines?

Yes, the Bluge Reader and Writer instances are safe for concurrent use.

> How much concurrency does a Writer or a Reader support?

There are no explicit limitations, you will have to find what levels of concurrency perform well in your use-case.  My experience has been that having a few goroutines using the Writer will help improve indexing throughput.  But, if you're really trying to saturate your disk I/O you will probably have to shard across multiple indexes as well.

There is usually less benefit to sharing Readers across goroutines, because internally we share/reuse all the segment data anyway.  For example, if you have 2 users hitting your search API, each being handled by their own goroutine.  Even if each call Reader() themselves, they're going to be returned the exact same snapshot.  So, even without explicitly sharing the Reader, Bluge is managing the sharing for you.

**Comment by szxp** [comment]
Thank you for your great and quick answer.

The Reader snapshot concept made me think a bit. Is it OK to use a single Reader during the lifetime of a program? 

My plan is to use a single component in a classified advertising website with the InMemoryOnlyConfig with a single Writer and a single Reader during the lifetime of the program. The app listens for ad update or delete events and uses the Writer to update or delete the doc in the index. Incoming search requests will use the single Reader for searching. Maybe opening a new Reader for every search would be better?

**Comment by mschoch** [comment]
Snapshots are isolated points in time so if you hold on to a snapshot for reuse, two things happen:
1. The searches run on this snapshot do not see data indexed after this snapshot
2. Resources associated with this snapshot cannot be freed

Most applications want to search the latest data, so they should always get a new snapshot, and close it when done.  If the index isn't changing, Bluge will return everyone the same snapshot anyway, no need to manage this reuse yourself.

There could be more extreme cases where you still have to revisit this, but I would start with a simple approach, have everyone get their own reader, until you determine this is the source of a problem.

**Comment by szxp** [comment]
Thank you very much for your help.
