### ISSUE TITLE
How can i search a numeric field?

### ISSUE THREAD

**Issue by hengfeiyang** [blugelabs/bluge#97]
How can i search a numeric field ?

i can use `TermQuery `to search a text or keyword field, but it seems not support numeric field.

**Comment by mschoch** [comment]
To search a numeric field, you should use the NumericRangeQuery:

https://github.com/blugelabs/bluge/blob/f34c4accbd91d52d6896d1dbab744987c9e71450/query.go#L1095
or
https://github.com/blugelabs/bluge/blob/f34c4accbd91d52d6896d1dbab744987c9e71450/query.go#L1103

Also, here is a test case.  It isn't the best example, because it's trying to illustrate/test something else, but it does index a numeric field, and query it by range: https://github.com/blugelabs/bluge/blob/f34c4accbd91d52d6896d1dbab744987c9e71450/search_test.go#L1275-L1327

**Comment by hengfeiyang** [comment]
thanks, it's ok to use `RangeQuery` can search numeric range.

If i want to search a fixed value, likes `Year: 2020`, is it possible to use `termQuery` for numeric?

**Comment by mschoch** [comment]
It is technically possible to search for a single value using a term query, but you are using details of the implementation that are not guaranteed to work in the future.  Specifically, in the future, we plan to use a more space-efficient encoding of the numeric fields index.  When we do that, term query would stop working to numeric values, but the NumericRangeQuery will be updated to work with the new implementation.

**Comment by hengfeiyang** [comment]
okay, thank you.
