### ISSUE TITLE
goembed support?

### ISSUE THREAD

**Issue by SirMetathyst** [blugelabs/bluge#99]
Would be great if bluge would support other input other than a filepath so we can create an index offline then embed the index into our application as an in-memory read only index.

**Comment by mschoch** [comment]
Bluge does not depend on filepath, but we do have convenience methods for it because it is common.

The Bluge open call requires a configuration.  The configuration includes choosing a Directory implementation.  And the most common directory implementation uses the filesystem (and takes the filepath you mentioned as an argument).

We do not currently support goembed, but we support a very similar option to include the index in an elf executable.  So, if you're interested, you can probably make goembed work by following the pattern.

The support for including a static index in an elf binary is here: https://github.com/blugelabs/bluge_directory_elf

And you can read the full blog post, where I describe how this is used to power the site search on blugelabs.com: https://blugelabs.com/blog/site-search/

**Comment by SirMetathyst** [comment]
Thanks for pointing me in this direction. I'll look into it.
